
[depot.x86_64-linux.fetchzip.registry-General]
name = "registries/General"
sha256 = "sha256-WfmgU1GuxVGn9yl/EQ7doYdnDUSMDi7SqCyEy8YamXY="
stripRoot = false
url = "https://pkg.julialang.org/registry/23338594-aafe-5451-b93e-139f81909106/93737299af624d55235fd13616742788b10c0ed3#registry.tar.gz"
